### PR TITLE
fix: updated docker-compose.yml to use redis-stack container

### LINKED ISSUE #12: Update `docker-compose.yml` to use the Redis Stack container.
Update the `docker-compose.yml` so that it uses the `redis/redis-stack` container rather than the `redismod` container.  You should be able to remove the `entrypoint` from the file as it will no longer be needed.

Test the demo application with your modified container to make sure that you can run it and interact with it.  Ensure that data in Redis persists between container restarts.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

### PR DESCRIPTION
**Pull request by mohdimran25**
Closes: #12 
Changed `redismod` container image with `redis/redis-stack` container image.
And also remove the `entrypoint` from the `docker-compose.yml`.
Application runs fine after the changes, gives the same output as before.

My twitter handle is: mohdimran_25. Thanks!

### CODE REVIEW

**Comment by SuzeShardlow** [comment]
Thanks for the PR @mohdimran25, we will review this in our daytime :)

**Review by simonprickett — APPROVED** [review]
Looks good and works for me - @SuzeShardlow good to merge.

**Comment by SuzeShardlow** [comment]
Thanks @mohdimran25!  If you are a member of our Discord server, please let us know your handle so we can give you the `Hacktoberfest` role :)

**Comment by SuzeShardlow** [comment]
Thanks @mohdimran25, I've given you the `Hacktoberfest 2022` role in our Discord server :)

**Pull request merged**
